# Generated by Django 5.0.3 on 2024-05-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='surname',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
