# Generated by Django 5.0.3 on 2024-03-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_team_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.CharField(default='', max_length=50),
        ),
    ]
