# Generated by Django 5.0.3 on 2024-05-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_player_name_alter_player_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tournament.player'),
        ),
    ]
