# Generated by Django 5.0.3 on 2024-03-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
