# Generated by Django 5.0.3 on 2025-05-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_match_dcr_match_dts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default='2025-06-05', verbose_name='Date'),
        ),
    ]
