# Generated by Django 5.0.3 on 2024-03-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_match_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default='20:00:00'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default='2024-06-05'),
        ),
    ]
