# Generated by Django 5.0.3 on 2024-03-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_match_time_alter_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pitch',
            field=models.CharField(default='da definire', max_length=50),
        ),
    ]
