# Generated by Django 5.0.3 on 2025-06-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
