# Generated by Django 5.0.3 on 2024-03-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_match_pitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(default='Group', max_length=50),
        ),
    ]
