# Generated by Django 5.0.3 on 2025-06-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_team_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='note',
            field=models.CharField(default='Gironi', max_length=500, verbose_name='Stage'),
        ),
    ]
