# Generated by Django 5.0.3 on 2025-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_match_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='note',
            field=models.CharField(default='Gironi', max_length=500, verbose_name='Note'),
        ),
    ]
