# Generated by Django 5.0.3 on 2024-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_alter_match_score1_alter_match_score2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pitch',
            field=models.CharField(choices=[('Blu', 'Blu'), ('Verde', 'Verde'), ('Da definire', 'Da definire')], default='Da definire', max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(default='Gironi', max_length=50),
        ),
    ]
