# Generated by Django 5.0.3 on 2025-06-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_alter_match_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Note'),
        ),
    ]
