# Generated by Django 5.0.3 on 2025-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_alter_match_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Note'),
        ),
    ]
