# Generated by Django 5.0.3 on 2026-01-13 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015__drop_pitch_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='AllOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_gkp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_gkp', to='tournament.player')),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='tournament.team')),
                ('mvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp', to='tournament.player')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='tournament.team')),
                ('third_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third', to='tournament.team')),
                ('top_scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_scorer', to='tournament.player')),
            ],
        ),
    ]
