# Generated by Django 5.0.3 on 2026-01-13 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_alter_team_name_alloffame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alloffame',
            name='best_gkp',
        ),
        migrations.RemoveField(
            model_name='alloffame',
            name='first_team',
        ),
        migrations.RemoveField(
            model_name='alloffame',
            name='mvp',
        ),
        migrations.RemoveField(
            model_name='alloffame',
            name='second_team',
        ),
        migrations.RemoveField(
            model_name='alloffame',
            name='third_team',
        ),
        migrations.RemoveField(
            model_name='alloffame',
            name='top_scorer',
        ),
        migrations.AddField(
            model_name='alloffame',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='tournament.player'),
        ),
        migrations.AddField(
            model_name='alloffame',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='alloffame',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alloffame',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
