# Generated by Django 5.0.3 on 2026-01-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_remove_alloffame_best_gkp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloffame',
            name='title',
            field=models.CharField(choices=[('1° Posto', 'First Place'), ('2° Posto', 'Second Place'), ('3° Posto', 'Third Place'), ('MVP', 'Mvp'), ('Capocannoniere', 'Top Scorer'), ('Miglior Portiere', 'Best Gk')], default='', max_length=50),
        ),
    ]
