# Generated by Django 5.0.3 on 2026-01-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_alter_alloffame_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('first_place', '1° Posto'), ('second_place', '2° Posto'), ('third_place', '3° Posto'), ('mvp', 'MVP'), ('top_scorer', 'Capocannoniere'), ('best_gk', 'Miglior Portiere')], default='first_place', max_length=50)),
                ('year', models.IntegerField(default=2026)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='tournament.player')),
                ('team', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team', to='tournament.team')),
            ],
        ),
        migrations.DeleteModel(
            name='AllOfFame',
        ),
    ]
