# Generated by Django 5.0.3 on 2026-01-13 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_halloffame_delete_alloffame'),
    ]

    operations = [
        migrations.AddField(
            model_name='halloffame',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='tournament.team'),
        ),
    ]
