# Generated by Django 5.0.3 on 2026-01-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_halloffame_team_name_alter_halloffame_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='halloffame',
            name='player_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
